apiVersion: apps/v1
kind: ReplicationController
metadata:
  labels:
    name: helloworld
  name: helloworld-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: helloworld
    spec:
      containers:
      - image: chdinnureddy/helloworld
        name: helloworld
        ports:
        - name: helloworld
          containerPort: 2222      
---
# Node Port Service
apiVersion: v1
kind: Service
metadata:
  labels:
    name: helloworld
  name: helloworld
spec:
  type: NodePort
  ports:
    - port: 2222
      targetPort: 2222
  selector:
    name: helloworld
---
